version: '3.6'
services:
  node-mongo-registration-login-api:
    build:
      context: .
    container_name: node-mongo-registration-login-api
    ports:
      - 4000:4000
  mongo:
    image: mongo:4
    container_name: mongo
    ports:
      - 27017:27017
networks:
  default:
    external:
      name: angular-nodejs-example